# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1606, 991)
        mainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.hlayout_import = QtWidgets.QHBoxLayout()
        self.hlayout_import.setObjectName("hlayout_import")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.linepath = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.linepath.setFont(font)
        self.linepath.setObjectName("linepath")
        self.horizontalLayout_2.addWidget(self.linepath)
        self.btnimportwo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnimportwo.sizePolicy().hasHeightForWidth())
        self.btnimportwo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.btnimportwo.setFont(font)
        self.btnimportwo.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.btnimportwo.setObjectName("btnimportwo")
        self.horizontalLayout_2.addWidget(self.btnimportwo)
        self.btnimportinvoice = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnimportinvoice.sizePolicy().hasHeightForWidth())
        self.btnimportinvoice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.btnimportinvoice.setFont(font)
        self.btnimportinvoice.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.btnimportinvoice.setObjectName("btnimportinvoice")
        self.horizontalLayout_2.addWidget(self.btnimportinvoice)
        self.hlayout_import.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.hlayout_import)
        self.lblpath = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblpath.setFont(font)
        self.lblpath.setStyleSheet("")
        self.lblpath.setObjectName("lblpath")
        self.verticalLayout.addWidget(self.lblpath)
        self.lblcost = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblcost.setFont(font)
        self.lblcost.setObjectName("lblcost")
        self.verticalLayout.addWidget(self.lblcost)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.layout_chk = QtWidgets.QGridLayout()
        self.layout_chk.setObjectName("layout_chk")
        self.chkelevators = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkelevators.setFont(font)
        self.chkelevators.setStyleSheet("")
        self.chkelevators.setObjectName("chkelevators")
        self.layout_chk.addWidget(self.chkelevators, 2, 5, 1, 1)
        self.chkoperating = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkoperating.setFont(font)
        self.chkoperating.setStyleSheet("")
        self.chkoperating.setObjectName("chkoperating")
        self.layout_chk.addWidget(self.chkoperating, 0, 2, 1, 1)
        self.chkcaretakers = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkcaretakers.setFont(font)
        self.chkcaretakers.setStyleSheet("")
        self.chkcaretakers.setObjectName("chkcaretakers")
        self.layout_chk.addWidget(self.chkcaretakers, 0, 3, 1, 1)
        self.chkplumbers = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkplumbers.setFont(font)
        self.chkplumbers.setStyleSheet("")
        self.chkplumbers.setObjectName("chkplumbers")
        self.layout_chk.addWidget(self.chkplumbers, 0, 0, 1, 1)
        self.chkcarpenters = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkcarpenters.setFont(font)
        self.chkcarpenters.setStyleSheet("")
        self.chkcarpenters.setObjectName("chkcarpenters")
        self.layout_chk.addWidget(self.chkcarpenters, 0, 1, 1, 1)
        self.chksteamfitters = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chksteamfitters.setFont(font)
        self.chksteamfitters.setStyleSheet("")
        self.chksteamfitters.setObjectName("chksteamfitters")
        self.layout_chk.addWidget(self.chksteamfitters, 0, 4, 1, 1)
        self.chkelectricians = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkelectricians.setFont(font)
        self.chkelectricians.setStyleSheet("")
        self.chkelectricians.setObjectName("chkelectricians")
        self.layout_chk.addWidget(self.chkelectricians, 2, 1, 1, 1)
        self.chkhazardous = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkhazardous.setFont(font)
        self.chkhazardous.setStyleSheet("")
        self.chkhazardous.setObjectName("chkhazardous")
        self.layout_chk.addWidget(self.chkhazardous, 0, 6, 1, 1)
        self.chkcontrol = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkcontrol.setFont(font)
        self.chkcontrol.setStyleSheet("")
        self.chkcontrol.setObjectName("chkcontrol")
        self.layout_chk.addWidget(self.chkcontrol, 2, 3, 1, 1)
        self.chktinsmiths = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chktinsmiths.setFont(font)
        self.chktinsmiths.setStyleSheet("")
        self.chktinsmiths.setObjectName("chktinsmiths")
        self.layout_chk.addWidget(self.chktinsmiths, 2, 4, 1, 1)
        self.chkmachinists = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkmachinists.setFont(font)
        self.chkmachinists.setStyleSheet("")
        self.chkmachinists.setObjectName("chkmachinists")
        self.layout_chk.addWidget(self.chkmachinists, 0, 5, 1, 1)
        self.chklocksmiths = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chklocksmiths.setFont(font)
        self.chklocksmiths.setStyleSheet("")
        self.chklocksmiths.setObjectName("chklocksmiths")
        self.layout_chk.addWidget(self.chklocksmiths, 2, 0, 1, 1)
        self.chkcampus = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkcampus.setFont(font)
        self.chkcampus.setStyleSheet("")
        self.chkcampus.setObjectName("chkcampus")
        self.layout_chk.addWidget(self.chkcampus, 2, 2, 1, 1)
        self.chkshift = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkshift.setFont(font)
        self.chkshift.setStyleSheet("")
        self.chkshift.setObjectName("chkshift")
        self.layout_chk.addWidget(self.chkshift, 2, 6, 1, 1)
        self.verticalLayout_5.addLayout(self.layout_chk)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.hlayout_buttons = QtWidgets.QHBoxLayout()
        self.hlayout_buttons.setObjectName("hlayout_buttons")
        self.vlayout_repair = QtWidgets.QVBoxLayout()
        self.vlayout_repair.setSpacing(10)
        self.vlayout_repair.setObjectName("vlayout_repair")
        self.btnrepair = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnrepair.sizePolicy().hasHeightForWidth())
        self.btnrepair.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnrepair.setFont(font)
        self.btnrepair.setStyleSheet("background-color: rgb(39, 108, 211); \n"
"color: white;")
        self.btnrepair.setCheckable(False)
        self.btnrepair.setObjectName("btnrepair")
        self.vlayout_repair.addWidget(self.btnrepair)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_service = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_service.setFont(font)
        self.btn_service.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btn_service.setCheckable(True)
        self.btn_service.setObjectName("btn_service")
        self.gridLayout.addWidget(self.btn_service, 1, 0, 1, 1)
        self.btnaccess = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnaccess.setFont(font)
        self.btnaccess.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btnaccess.setCheckable(True)
        self.btnaccess.setObjectName("btnaccess")
        self.gridLayout.addWidget(self.btnaccess, 0, 4, 1, 1)
        self.btnremidiation = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnremidiation.setFont(font)
        self.btnremidiation.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btnremidiation.setCheckable(True)
        self.btnremidiation.setObjectName("btnremidiation")
        self.gridLayout.addWidget(self.btnremidiation, 0, 0, 1, 1)
        self.btnchange = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnchange.setFont(font)
        self.btnchange.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btnchange.setCheckable(True)
        self.btnchange.setObjectName("btnchange")
        self.gridLayout.addWidget(self.btnchange, 0, 1, 1, 1)
        self.btnassistance = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnassistance.setFont(font)
        self.btnassistance.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btnassistance.setCheckable(True)
        self.btnassistance.setObjectName("btnassistance")
        self.gridLayout.addWidget(self.btnassistance, 1, 4, 1, 1)
        self.btncleaning = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncleaning.setFont(font)
        self.btncleaning.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btncleaning.setCheckable(True)
        self.btncleaning.setObjectName("btncleaning")
        self.gridLayout.addWidget(self.btncleaning, 0, 6, 1, 1)
        self.btnsupply = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnsupply.setFont(font)
        self.btnsupply.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btnsupply.setCheckable(True)
        self.btnsupply.setObjectName("btnsupply")
        self.gridLayout.addWidget(self.btnsupply, 0, 2, 1, 1)
        self.btncleaning_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncleaning_2.setFont(font)
        self.btncleaning_2.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btncleaning_2.setCheckable(True)
        self.btncleaning_2.setObjectName("btncleaning_2")
        self.gridLayout.addWidget(self.btncleaning_2, 1, 6, 1, 1)
        self.btnseperation = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnseperation.setFont(font)
        self.btnseperation.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btnseperation.setCheckable(True)
        self.btnseperation.setObjectName("btnseperation")
        self.gridLayout.addWidget(self.btnseperation, 1, 2, 1, 1)
        self.btnmanufacture = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnmanufacture.setFont(font)
        self.btnmanufacture.setStyleSheet("background-color:  rgb(3, 196, 255)")
        self.btnmanufacture.setCheckable(True)
        self.btnmanufacture.setObjectName("btnmanufacture")
        self.gridLayout.addWidget(self.btnmanufacture, 1, 1, 1, 1)
        self.vlayout_repair.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnwear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnwear.setFont(font)
        self.btnwear.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnwear.setCheckable(True)
        self.btnwear.setObjectName("btnwear")
        self.gridLayout_2.addWidget(self.btnwear, 2, 2, 1, 1)
        self.btnalarm = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnalarm.setFont(font)
        self.btnalarm.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnalarm.setCheckable(True)
        self.btnalarm.setObjectName("btnalarm")
        self.gridLayout_2.addWidget(self.btnalarm, 0, 3, 1, 1)
        self.btnsafety = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnsafety.setFont(font)
        self.btnsafety.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnsafety.setCheckable(True)
        self.btnsafety.setObjectName("btnsafety")
        self.gridLayout_2.addWidget(self.btnsafety, 1, 0, 1, 1)
        self.btnburning = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnburning.setFont(font)
        self.btnburning.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnburning.setCheckable(True)
        self.btnburning.setObjectName("btnburning")
        self.gridLayout_2.addWidget(self.btnburning, 1, 3, 1, 1)
        self.btnequipment = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnequipment.setFont(font)
        self.btnequipment.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnequipment.setCheckable(True)
        self.btnequipment.setObjectName("btnequipment")
        self.gridLayout_2.addWidget(self.btnequipment, 0, 0, 1, 1)
        self.btnother = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnother.setFont(font)
        self.btnother.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnother.setCheckable(True)
        self.btnother.setObjectName("btnother")
        self.gridLayout_2.addWidget(self.btnother, 2, 3, 1, 1)
        self.btnnoise = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnnoise.setFont(font)
        self.btnnoise.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnnoise.setCheckable(True)
        self.btnnoise.setObjectName("btnnoise")
        self.gridLayout_2.addWidget(self.btnnoise, 2, 1, 1, 1)
        self.btnoperational = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnoperational.setFont(font)
        self.btnoperational.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnoperational.setCheckable(True)
        self.btnoperational.setObjectName("btnoperational")
        self.gridLayout_2.addWidget(self.btnoperational, 0, 1, 1, 1)
        self.btnspace = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnspace.setFont(font)
        self.btnspace.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnspace.setCheckable(True)
        self.btnspace.setObjectName("btnspace")
        self.gridLayout_2.addWidget(self.btnspace, 1, 1, 1, 1)
        self.btnwater = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnwater.setFont(font)
        self.btnwater.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnwater.setCheckable(True)
        self.btnwater.setObjectName("btnwater")
        self.gridLayout_2.addWidget(self.btnwater, 2, 0, 1, 1)
        self.btnleak = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnleak.setFont(font)
        self.btnleak.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnleak.setCheckable(True)
        self.btnleak.setObjectName("btnleak")
        self.gridLayout_2.addWidget(self.btnleak, 1, 2, 1, 1)
        self.btnlighting = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnlighting.setFont(font)
        self.btnlighting.setStyleSheet("background-color: rgb(0, 232, 232)")
        self.btnlighting.setCheckable(True)
        self.btnlighting.setObjectName("btnlighting")
        self.gridLayout_2.addWidget(self.btnlighting, 0, 2, 1, 1)
        self.vlayout_repair.addLayout(self.gridLayout_2)
        self.vlayout_repair.setStretch(0, 2)
        self.vlayout_repair.setStretch(2, 1)
        self.hlayout_buttons.addLayout(self.vlayout_repair)
        self.vlayout_quality = QtWidgets.QVBoxLayout()
        self.vlayout_quality.setObjectName("vlayout_quality")
        self.btnquality = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnquality.sizePolicy().hasHeightForWidth())
        self.btnquality.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnquality.setFont(font)
        self.btnquality.setStyleSheet("background-color: rgb(0, 149, 0); \n"
"color: white;")
        self.btnquality.setCheckable(False)
        self.btnquality.setObjectName("btnquality")
        self.vlayout_quality.addWidget(self.btnquality)
        self.btninspection = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btninspection.sizePolicy().hasHeightForWidth())
        self.btninspection.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btninspection.setFont(font)
        self.btninspection.setStyleSheet("background-color:rgb(145, 217, 0)")
        self.btninspection.setCheckable(True)
        self.btninspection.setObjectName("btninspection")
        self.vlayout_quality.addWidget(self.btninspection)
        self.btntest = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btntest.sizePolicy().hasHeightForWidth())
        self.btntest.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btntest.setFont(font)
        self.btntest.setStyleSheet("background-color:rgb(145, 217, 0)")
        self.btntest.setCheckable(True)
        self.btntest.setObjectName("btntest")
        self.vlayout_quality.addWidget(self.btntest)
        self.btnpower = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnpower.sizePolicy().hasHeightForWidth())
        self.btnpower.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnpower.setFont(font)
        self.btnpower.setStyleSheet("background-color:rgb(145, 217, 0)")
        self.btnpower.setCheckable(True)
        self.btnpower.setObjectName("btnpower")
        self.vlayout_quality.addWidget(self.btnpower)
        self.btndocumentation = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btndocumentation.sizePolicy().hasHeightForWidth())
        self.btndocumentation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btndocumentation.setFont(font)
        self.btndocumentation.setStyleSheet("background-color:rgb(145, 217, 0)")
        self.btndocumentation.setCheckable(True)
        self.btndocumentation.setObjectName("btndocumentation")
        self.vlayout_quality.addWidget(self.btndocumentation)
        self.btnscheduled = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnscheduled.sizePolicy().hasHeightForWidth())
        self.btnscheduled.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnscheduled.setFont(font)
        self.btnscheduled.setStyleSheet("background-color:rgb(145, 217, 0)")
        self.btnscheduled.setCheckable(True)
        self.btnscheduled.setObjectName("btnscheduled")
        self.vlayout_quality.addWidget(self.btnscheduled)
        self.vlayout_quality.setStretch(0, 2)
        self.vlayout_quality.setStretch(1, 1)
        self.vlayout_quality.setStretch(2, 1)
        self.vlayout_quality.setStretch(3, 1)
        self.vlayout_quality.setStretch(4, 1)
        self.vlayout_quality.setStretch(5, 1)
        self.hlayout_buttons.addLayout(self.vlayout_quality)
        self.vlayout_security = QtWidgets.QVBoxLayout()
        self.vlayout_security.setObjectName("vlayout_security")
        self.btnsecurity = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnsecurity.sizePolicy().hasHeightForWidth())
        self.btnsecurity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnsecurity.setFont(font)
        self.btnsecurity.setStyleSheet("background-color: rgb(234, 153, 59);\n"
"color: white;")
        self.btnsecurity.setCheckable(False)
        self.btnsecurity.setObjectName("btnsecurity")
        self.vlayout_security.addWidget(self.btnsecurity)
        self.btnaccess_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnaccess_2.sizePolicy().hasHeightForWidth())
        self.btnaccess_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnaccess_2.setFont(font)
        self.btnaccess_2.setStyleSheet("background-color: rgb(252, 195, 95)\n"
"")
        self.btnaccess_2.setCheckable(True)
        self.btnaccess_2.setObjectName("btnaccess_2")
        self.vlayout_security.addWidget(self.btnaccess_2)
        self.btncontractor = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncontractor.sizePolicy().hasHeightForWidth())
        self.btncontractor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncontractor.setFont(font)
        self.btncontractor.setStyleSheet("background-color: rgb(252, 195, 95)\n"
"")
        self.btncontractor.setCheckable(True)
        self.btncontractor.setObjectName("btncontractor")
        self.vlayout_security.addWidget(self.btncontractor)
        self.btnkey = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnkey.sizePolicy().hasHeightForWidth())
        self.btnkey.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnkey.setFont(font)
        self.btnkey.setStyleSheet("background-color: rgb(252, 195, 95)\n"
"")
        self.btnkey.setCheckable(True)
        self.btnkey.setObjectName("btnkey")
        self.vlayout_security.addWidget(self.btnkey)
        self.vlayout_security.setStretch(0, 2)
        self.vlayout_security.setStretch(1, 1)
        self.vlayout_security.setStretch(2, 1)
        self.vlayout_security.setStretch(3, 1)
        self.hlayout_buttons.addLayout(self.vlayout_security)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnothers = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnothers.setFont(font)
        self.btnothers.setAutoFillBackground(False)
        self.btnothers.setStyleSheet("background-color: rgb(130, 130, 130); \n"
"color: white;")
        self.btnothers.setCheckable(False)
        self.btnothers.setObjectName("btnothers")
        self.verticalLayout_2.addWidget(self.btnothers)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.btnmobile = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnmobile.setFont(font)
        self.btnmobile.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.btnmobile.setCheckable(True)
        self.btnmobile.setObjectName("btnmobile")
        self.verticalLayout_2.addWidget(self.btnmobile)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.btnnone = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnnone.setFont(font)
        self.btnnone.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.btnnone.setCheckable(True)
        self.btnnone.setObjectName("btnnone")
        self.verticalLayout_2.addWidget(self.btnnone)
        self.hlayout_buttons.addLayout(self.verticalLayout_2)
        self.verticalLayout_12.addLayout(self.hlayout_buttons)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btntoilet = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btntoilet.sizePolicy().hasHeightForWidth())
        self.btntoilet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btntoilet.setFont(font)
        self.btntoilet.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btntoilet.setCheckable(True)
        self.btntoilet.setObjectName("btntoilet")
        self.verticalLayout_3.addWidget(self.btntoilet)
        self.btnsink = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnsink.sizePolicy().hasHeightForWidth())
        self.btnsink.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnsink.setFont(font)
        self.btnsink.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnsink.setCheckable(True)
        self.btnsink.setObjectName("btnsink")
        self.verticalLayout_3.addWidget(self.btnsink)
        self.btnfountains = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnfountains.sizePolicy().hasHeightForWidth())
        self.btnfountains.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnfountains.setFont(font)
        self.btnfountains.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnfountains.setCheckable(True)
        self.btnfountains.setObjectName("btnfountains")
        self.verticalLayout_3.addWidget(self.btnfountains)
        self.btnsewage = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnsewage.sizePolicy().hasHeightForWidth())
        self.btnsewage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnsewage.setFont(font)
        self.btnsewage.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnsewage.setCheckable(True)
        self.btnsewage.setObjectName("btnsewage")
        self.verticalLayout_3.addWidget(self.btnsewage)
        self.btnshower = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnshower.sizePolicy().hasHeightForWidth())
        self.btnshower.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnshower.setFont(font)
        self.btnshower.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnshower.setCheckable(True)
        self.btnshower.setObjectName("btnshower")
        self.verticalLayout_3.addWidget(self.btnshower)
        self.btnhose = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnhose.sizePolicy().hasHeightForWidth())
        self.btnhose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnhose.setFont(font)
        self.btnhose.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnhose.setCheckable(True)
        self.btnhose.setObjectName("btnhose")
        self.verticalLayout_3.addWidget(self.btnhose)
        self.btnbackflow = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnbackflow.sizePolicy().hasHeightForWidth())
        self.btnbackflow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnbackflow.setFont(font)
        self.btnbackflow.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnbackflow.setCheckable(True)
        self.btnbackflow.setObjectName("btnbackflow")
        self.verticalLayout_3.addWidget(self.btnbackflow)
        self.btnwater_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnwater_2.sizePolicy().hasHeightForWidth())
        self.btnwater_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnwater_2.setFont(font)
        self.btnwater_2.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnwater_2.setCheckable(True)
        self.btnwater_2.setObjectName("btnwater_2")
        self.verticalLayout_3.addWidget(self.btnwater_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btndoor = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btndoor.sizePolicy().hasHeightForWidth())
        self.btndoor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btndoor.setFont(font)
        self.btndoor.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btndoor.setCheckable(True)
        self.btndoor.setObjectName("btndoor")
        self.verticalLayout_4.addWidget(self.btndoor)
        self.btnfobs = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnfobs.sizePolicy().hasHeightForWidth())
        self.btnfobs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnfobs.setFont(font)
        self.btnfobs.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnfobs.setCheckable(True)
        self.btnfobs.setObjectName("btnfobs")
        self.verticalLayout_4.addWidget(self.btnfobs)
        self.btnaccessbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnaccessbutton.sizePolicy().hasHeightForWidth())
        self.btnaccessbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnaccessbutton.setFont(font)
        self.btnaccessbutton.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnaccessbutton.setCheckable(True)
        self.btnaccessbutton.setObjectName("btnaccessbutton")
        self.verticalLayout_4.addWidget(self.btnaccessbutton)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnelectrical = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnelectrical.sizePolicy().hasHeightForWidth())
        self.btnelectrical.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnelectrical.setFont(font)
        self.btnelectrical.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnelectrical.setCheckable(True)
        self.btnelectrical.setObjectName("btnelectrical")
        self.verticalLayout_6.addWidget(self.btnelectrical)
        self.btnlighting_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnlighting_2.sizePolicy().hasHeightForWidth())
        self.btnlighting_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnlighting_2.setFont(font)
        self.btnlighting_2.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnlighting_2.setCheckable(True)
        self.btnlighting_2.setObjectName("btnlighting_2")
        self.verticalLayout_6.addWidget(self.btnlighting_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnvalves = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnvalves.sizePolicy().hasHeightForWidth())
        self.btnvalves.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnvalves.setFont(font)
        self.btnvalves.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnvalves.setCheckable(True)
        self.btnvalves.setObjectName("btnvalves")
        self.verticalLayout_7.addWidget(self.btnvalves)
        self.btnhvac = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnhvac.sizePolicy().hasHeightForWidth())
        self.btnhvac.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnhvac.setFont(font)
        self.btnhvac.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnhvac.setCheckable(True)
        self.btnhvac.setObjectName("btnhvac")
        self.verticalLayout_7.addWidget(self.btnhvac)
        self.btnfluid = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnfluid.sizePolicy().hasHeightForWidth())
        self.btnfluid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnfluid.setFont(font)
        self.btnfluid.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnfluid.setCheckable(True)
        self.btnfluid.setObjectName("btnfluid")
        self.verticalLayout_7.addWidget(self.btnfluid)
        self.btnchillers = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnchillers.sizePolicy().hasHeightForWidth())
        self.btnchillers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnchillers.setFont(font)
        self.btnchillers.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnchillers.setCheckable(True)
        self.btnchillers.setObjectName("btnchillers")
        self.verticalLayout_7.addWidget(self.btnchillers)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnceiling = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnceiling.sizePolicy().hasHeightForWidth())
        self.btnceiling.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnceiling.setFont(font)
        self.btnceiling.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnceiling.setCheckable(True)
        self.btnceiling.setObjectName("btnceiling")
        self.verticalLayout_8.addWidget(self.btnceiling)
        self.btnrailing = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnrailing.sizePolicy().hasHeightForWidth())
        self.btnrailing.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnrailing.setFont(font)
        self.btnrailing.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnrailing.setCheckable(True)
        self.btnrailing.setObjectName("btnrailing")
        self.verticalLayout_8.addWidget(self.btnrailing)
        self.btnscaffolds = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnscaffolds.sizePolicy().hasHeightForWidth())
        self.btnscaffolds.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnscaffolds.setFont(font)
        self.btnscaffolds.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnscaffolds.setCheckable(True)
        self.btnscaffolds.setObjectName("btnscaffolds")
        self.verticalLayout_8.addWidget(self.btnscaffolds)
        self.btninsulation = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btninsulation.sizePolicy().hasHeightForWidth())
        self.btninsulation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btninsulation.setFont(font)
        self.btninsulation.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btninsulation.setCheckable(True)
        self.btninsulation.setObjectName("btninsulation")
        self.verticalLayout_8.addWidget(self.btninsulation)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnwaste = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnwaste.sizePolicy().hasHeightForWidth())
        self.btnwaste.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnwaste.setFont(font)
        self.btnwaste.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnwaste.setCheckable(True)
        self.btnwaste.setObjectName("btnwaste")
        self.verticalLayout_9.addWidget(self.btnwaste)
        self.btnevents = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnevents.sizePolicy().hasHeightForWidth())
        self.btnevents.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnevents.setFont(font)
        self.btnevents.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnevents.setCheckable(True)
        self.btnevents.setObjectName("btnevents")
        self.verticalLayout_9.addWidget(self.btnevents)
        self.btnfilm = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnfilm.sizePolicy().hasHeightForWidth())
        self.btnfilm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnfilm.setFont(font)
        self.btnfilm.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnfilm.setCheckable(True)
        self.btnfilm.setObjectName("btnfilm")
        self.verticalLayout_9.addWidget(self.btnfilm)
        self.btnnitrogen = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnnitrogen.sizePolicy().hasHeightForWidth())
        self.btnnitrogen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnnitrogen.setFont(font)
        self.btnnitrogen.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnnitrogen.setCheckable(True)
        self.btnnitrogen.setObjectName("btnnitrogen")
        self.verticalLayout_9.addWidget(self.btnnitrogen)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btnrestroom = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnrestroom.sizePolicy().hasHeightForWidth())
        self.btnrestroom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnrestroom.setFont(font)
        self.btnrestroom.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnrestroom.setCheckable(True)
        self.btnrestroom.setObjectName("btnrestroom")
        self.verticalLayout_10.addWidget(self.btnrestroom)
        self.btnfurniture = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnfurniture.sizePolicy().hasHeightForWidth())
        self.btnfurniture.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnfurniture.setFont(font)
        self.btnfurniture.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnfurniture.setCheckable(True)
        self.btnfurniture.setObjectName("btnfurniture")
        self.verticalLayout_10.addWidget(self.btnfurniture)
        self.btncomputers = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncomputers.sizePolicy().hasHeightForWidth())
        self.btncomputers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncomputers.setFont(font)
        self.btncomputers.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btncomputers.setCheckable(True)
        self.btncomputers.setObjectName("btncomputers")
        self.verticalLayout_10.addWidget(self.btncomputers)
        self.btnkitchen = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnkitchen.sizePolicy().hasHeightForWidth())
        self.btnkitchen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnkitchen.setFont(font)
        self.btnkitchen.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnkitchen.setCheckable(True)
        self.btnkitchen.setObjectName("btnkitchen")
        self.verticalLayout_10.addWidget(self.btnkitchen)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btnmetal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnmetal.sizePolicy().hasHeightForWidth())
        self.btnmetal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnmetal.setFont(font)
        self.btnmetal.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnmetal.setCheckable(True)
        self.btnmetal.setObjectName("btnmetal")
        self.verticalLayout_11.addWidget(self.btnmetal)
        self.btnducts = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnducts.sizePolicy().hasHeightForWidth())
        self.btnducts.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnducts.setFont(font)
        self.btnducts.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnducts.setCheckable(True)
        self.btnducts.setObjectName("btnducts")
        self.verticalLayout_11.addWidget(self.btnducts)
        self.btnmachine = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnmachine.sizePolicy().hasHeightForWidth())
        self.btnmachine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnmachine.setFont(font)
        self.btnmachine.setStyleSheet("background-color: rgb(161, 255, 200)")
        self.btnmachine.setCheckable(True)
        self.btnmachine.setObjectName("btnmachine")
        self.verticalLayout_11.addWidget(self.btnmachine)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.lblfilter = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblfilter.setFont(font)
        self.lblfilter.setText("")
        self.lblfilter.setObjectName("lblfilter")
        self.horizontalLayout_5.addWidget(self.lblfilter)
        self.btnfilter = QtWidgets.QPushButton(self.centralwidget)
        self.btnfilter.setMinimumSize(QtCore.QSize(40, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btnfilter.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnfilter.setFont(font)
        self.btnfilter.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.btnfilter.setObjectName("btnfilter")
        self.horizontalLayout_5.addWidget(self.btnfilter)
        self.btnexport = QtWidgets.QPushButton(self.centralwidget)
        self.btnexport.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.btnexport.setObjectName("btnexport")
        self.horizontalLayout_5.addWidget(self.btnexport)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chkPaid = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkPaid.setFont(font)
        self.chkPaid.setObjectName("chkPaid")
        self.gridLayout_3.addWidget(self.chkPaid, 0, 1, 1, 1)
        self.chkTopCharged = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkTopCharged.setFont(font)
        self.chkTopCharged.setObjectName("chkTopCharged")
        self.gridLayout_3.addWidget(self.chkTopCharged, 0, 3, 1, 1)
        self.chkCharged = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkCharged.setFont(font)
        self.chkCharged.setObjectName("chkCharged")
        self.gridLayout_3.addWidget(self.chkCharged, 0, 2, 1, 1)
        self.chkHours = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkHours.setFont(font)
        self.chkHours.setObjectName("chkHours")
        self.gridLayout_3.addWidget(self.chkHours, 1, 1, 1, 1)
        self.chkWC = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkWC.setFont(font)
        self.chkWC.setObjectName("chkWC")
        self.gridLayout_3.addWidget(self.chkWC, 1, 0, 1, 1)
        self.chkTopPaid = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkTopPaid.setFont(font)
        self.chkTopPaid.setObjectName("chkTopPaid")
        self.gridLayout_3.addWidget(self.chkTopPaid, 1, 2, 1, 1)
        self.chkTopHours = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkTopHours.setFont(font)
        self.chkTopHours.setObjectName("chkTopHours")
        self.gridLayout_3.addWidget(self.chkTopHours, 1, 3, 1, 1)
        self.chkBuilding = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkBuilding.setFont(font)
        self.chkBuilding.setObjectName("chkBuilding")
        self.gridLayout_3.addWidget(self.chkBuilding, 0, 0, 1, 1)
        self.btnreport = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnreport.sizePolicy().hasHeightForWidth())
        self.btnreport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnreport.setFont(font)
        self.btnreport.setStyleSheet("background-color: #336699;\n"
"color: white\n"
"")
        self.btnreport.setObjectName("btnreport")
        self.gridLayout_3.addWidget(self.btnreport, 0, 4, 1, 1)
        self.lblReport = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblReport.setFont(font)
        self.lblReport.setText("")
        self.lblReport.setObjectName("lblReport")
        self.gridLayout_3.addWidget(self.lblReport, 1, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(1567, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1606, 22))
        self.menubar.setStyleSheet("background_color:rgb(0, 0, 127);\n"
"")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(mainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport_Report = QtWidgets.QAction(mainWindow)
        self.actionExport_Report.setObjectName("actionExport_Report")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport_Report)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.btnimportwo.setText(_translate("mainWindow", "Import WO descriptions"))
        self.btnimportinvoice.setText(_translate("mainWindow", "Import Invoices"))
        self.lblpath.setText(_translate("mainWindow", "No files imported yet."))
        self.lblcost.setText(_translate("mainWindow", "No invoices imported yet"))
        self.label.setText(_translate("mainWindow", "Work Centers"))
        self.chkelevators.setText(_translate("mainWindow", "Elevator Mechanics"))
        self.chkoperating.setText(_translate("mainWindow", "Operating Engineers"))
        self.chkcaretakers.setText(_translate("mainWindow", "Caretakers"))
        self.chkplumbers.setText(_translate("mainWindow", "Plumbers"))
        self.chkcarpenters.setText(_translate("mainWindow", "Carpenters"))
        self.chksteamfitters.setText(_translate("mainWindow", "Steamfitters"))
        self.chkelectricians.setText(_translate("mainWindow", "Electricians"))
        self.chkhazardous.setText(_translate("mainWindow", "Hazardous Materials Group"))
        self.chkcontrol.setText(_translate("mainWindow", "Control Technicians"))
        self.chktinsmiths.setText(_translate("mainWindow", "Tinsmiths"))
        self.chkmachinists.setText(_translate("mainWindow", "Machinists"))
        self.chklocksmiths.setText(_translate("mainWindow", "Locksmiths"))
        self.chkcampus.setText(_translate("mainWindow", "Campus Services"))
        self.chkshift.setText(_translate("mainWindow", "Shift Engineers"))
        self.label_2.setText(_translate("mainWindow", "Actoins & Issues"))
        self.btnrepair.setText(_translate("mainWindow", "Repair and Maintenance"))
        self.btn_service.setText(_translate("mainWindow", "Service"))
        self.btnaccess.setText(_translate("mainWindow", "Cutting Access"))
        self.btnremidiation.setText(_translate("mainWindow", "Remediation"))
        self.btnchange.setText(_translate("mainWindow", "Change and Replace"))
        self.btnassistance.setText(_translate("mainWindow", "Assistance"))
        self.btncleaning.setText(_translate("mainWindow", "Cleaning"))
        self.btnsupply.setText(_translate("mainWindow", "Supply and Installation"))
        self.btncleaning_2.setText(_translate("mainWindow", "Moving and Delivery"))
        self.btnseperation.setText(_translate("mainWindow", "Separation and Deconstruction"))
        self.btnmanufacture.setText(_translate("mainWindow", "Manufacture"))
        self.btnwear.setText(_translate("mainWindow", "Wear and Corrosion"))
        self.btnalarm.setText(_translate("mainWindow", "Alarms"))
        self.btnsafety.setText(_translate("mainWindow", "Safety and Hazards"))
        self.btnburning.setText(_translate("mainWindow", "Burning and Odor"))
        self.btnequipment.setText(_translate("mainWindow", "Equipment and Component Issues"))
        self.btnother.setText(_translate("mainWindow", "Other Emergency"))
        self.btnnoise.setText(_translate("mainWindow", "Noise and Sound"))
        self.btnoperational.setText(_translate("mainWindow", "Operational Functionality"))
        self.btnspace.setText(_translate("mainWindow", "Space Comfort Issues"))
        self.btnwater.setText(_translate("mainWindow", "Water-Steam Flow Issues"))
        self.btnleak.setText(_translate("mainWindow", "Leakage and Spillage"))
        self.btnlighting.setText(_translate("mainWindow", "Lighting Issues"))
        self.btnquality.setText(_translate("mainWindow", "Quality Control"))
        self.btninspection.setText(_translate("mainWindow", "Inspection and Coordination"))
        self.btntest.setText(_translate("mainWindow", "Testing and Assessment"))
        self.btnpower.setText(_translate("mainWindow", "Power and Shutdown Requests"))
        self.btndocumentation.setText(_translate("mainWindow", "Documentation and Reporting"))
        self.btnscheduled.setText(_translate("mainWindow", "Scheduled Activities"))
        self.btnsecurity.setText(_translate("mainWindow", "Security and Access"))
        self.btnaccess_2.setText(_translate("mainWindow", "Access Requests"))
        self.btncontractor.setText(_translate("mainWindow", "Contractor Access"))
        self.btnkey.setText(_translate("mainWindow", "Key Services"))
        self.btnothers.setText(_translate("mainWindow", "Other"))
        self.pushButton.setText(_translate("mainWindow", "Follow up"))
        self.pushButton_2.setText(_translate("mainWindow", "Standing order"))
        self.btnmobile.setText(_translate("mainWindow", "Mobile status"))
        self.pushButton_4.setText(_translate("mainWindow", "Billing and Time Keeping"))
        self.pushButton_5.setText(_translate("mainWindow", "Work Order Management"))
        self.btnnone.setText(_translate("mainWindow", "Non-classified"))
        self.label_3.setText(_translate("mainWindow", "Systems"))
        self.btntoilet.setText(_translate("mainWindow", "Toilet and Urinal"))
        self.btnsink.setText(_translate("mainWindow", "Sink and Faucet"))
        self.btnfountains.setText(_translate("mainWindow", "Fountains and Eyewash"))
        self.btnsewage.setText(_translate("mainWindow", "Sewage and Drainage"))
        self.btnshower.setText(_translate("mainWindow", "Shower"))
        self.btnhose.setText(_translate("mainWindow", "Hose and Sprinkler"))
        self.btnbackflow.setText(_translate("mainWindow", "Backflow Preventer"))
        self.btnwater_2.setText(_translate("mainWindow", "Water Distribution"))
        self.btndoor.setText(_translate("mainWindow", "Door, Window, Hardware"))
        self.btnfobs.setText(_translate("mainWindow", "Fobs and Readers"))
        self.btnaccessbutton.setText(_translate("mainWindow", "Accessibility Buttons"))
        self.btnelectrical.setText(_translate("mainWindow", "Electrical systems"))
        self.btnlighting_2.setText(_translate("mainWindow", "Lighting systems"))
        self.btnvalves.setText(_translate("mainWindow", "Valves and Controllers"))
        self.btnhvac.setText(_translate("mainWindow", "HVAC and AC"))
        self.btnfluid.setText(_translate("mainWindow", "Fluid Handling Equipment"))
        self.btnchillers.setText(_translate("mainWindow", "Chillers and Boilers"))
        self.btnceiling.setText(_translate("mainWindow", "Ceiling and Flooring"))
        self.btnrailing.setText(_translate("mainWindow", "Railing"))
        self.btnscaffolds.setText(_translate("mainWindow", "Scaffolds and Supports"))
        self.btninsulation.setText(_translate("mainWindow", "Insulation"))
        self.btnwaste.setText(_translate("mainWindow", "Waste and Recycling"))
        self.btnevents.setText(_translate("mainWindow", "Events and Conferences"))
        self.btnfilm.setText(_translate("mainWindow", "Film shoot"))
        self.btnnitrogen.setText(_translate("mainWindow", "Nitrogen Cylinders"))
        self.btnrestroom.setText(_translate("mainWindow", "Restroom Facilities"))
        self.btnfurniture.setText(_translate("mainWindow", "Furniture"))
        self.btncomputers.setText(_translate("mainWindow", "Computers and equipment"))
        self.btnkitchen.setText(_translate("mainWindow", "Kitchen Appliances"))
        self.btnmetal.setText(_translate("mainWindow", "Metal Sheets and Covers"))
        self.btnducts.setText(_translate("mainWindow", "Ducts and Induction"))
        self.btnmachine.setText(_translate("mainWindow", "Machine Shop Equipment"))
        self.btnfilter.setText(_translate("mainWindow", "Filter"))
        self.btnexport.setText(_translate("mainWindow", "Export Work Orders"))
        self.label_4.setText(_translate("mainWindow", "Report Generation"))
        self.chkPaid.setText(_translate("mainWindow", "Total Paid Distribution"))
        self.chkTopCharged.setText(_translate("mainWindow", "Top 10 Buildings By Total Charged"))
        self.chkCharged.setText(_translate("mainWindow", "Total Charged Distribution"))
        self.chkHours.setText(_translate("mainWindow", "Total Hours Distribution"))
        self.chkWC.setText(_translate("mainWindow", "Work Center KPIs"))
        self.chkTopPaid.setText(_translate("mainWindow", "Top 10 Buildings by Total Paid"))
        self.chkTopHours.setText(_translate("mainWindow", "Top 10 Buildings By Total Hours"))
        self.chkBuilding.setText(_translate("mainWindow", "Building KPIs"))
        self.btnreport.setText(_translate("mainWindow", "Generate Report"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionImport.setText(_translate("mainWindow", "Import"))
        self.actionExport_Report.setText(_translate("mainWindow", "Export Report"))
